version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - 27017
  node:
    image: node
    command: npm --prefix /app run dev
    ports:
      - 80:3000
    volumes:
      - .:/app
    depends_on:
      - mongo
    links:
      - mongo
